//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekTarifleri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarifler()
        {
            this.Malzemeler = new HashSet<Malzemeler>();
            this.Resimler = new HashSet<Resimler>();
            this.YapimAsamalari = new HashSet<YapimAsamalari>();
            this.Yorumlar = new HashSet<Yorumlar>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string YSuresi { get; set; }
        public string Porsiyon { get; set; }
        public bool Durum { get; set; }
        public System.DateTime OTarihi { get; set; }
        public string UserId { get; set; }
        public int KategoriId { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Malzemeler> Malzemeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resimler> Resimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YapimAsamalari> YapimAsamalari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
    }
}
